config/routes.rb
Rails.application.routes.draw do
  resources :membership_confirmations, only: [:create, :destroy]
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :styles, only: [:show, :index, :destroy]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to: 'ratings#new'
  post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  post 'freeze', to: 'users#freeze'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'ngbrewerylist', to:'breweries#nglist'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  post 'confirm', to: 'membership_confirmations#confirm'

end

app/models/user.rb
class User < ActiveRecord::Base
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true,
                       length: { minimum: 3 }

  validates_format_of :password, with: /(?=.*[A-Z])(?=.{4,}).+/, on: :create

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_many :membership_confirmations, dependent: :destroy

  def to_s
    username.to_s
  end

  def favorite_beer
    return nil if ratings.empty?
    ratings.order(score: :desc).limit(1).first.beer
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:ratings,:beers).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
	@ratings = Rating.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :root, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
    if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def freeze
   user = User.find(params[:id])
   user.update_attribute(:disabled, true)
   redirect_to :back
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user.admin? and user.disabled? %>
            <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @user.username %>
</h2>

<p>
  Has made <%= pluralize(@user.ratings.count, 'rating') %>
</p>

<% if @user.beer_clubs.any? %>
  <p>
    Member of
    <% @user.beer_clubs.each do |club| %>
      <%= link_to club.name, club %>
    <% end %>
  </p>
  <p>
    Pending applications
    <ul>
    <% @user.beer_clubs.each do |club| %>
      <% if club.membership_confirmations.any? %>
        <% club.membership_confirmations.each do |membership_confirmation| %>
          <li><%= membership_confirmation.user %> - <%= membership_confirmation.beer_club %>
            <%= link_to 'Confirm',confirm_url(id:membership_confirmation.id), method: :post %></li>

        <% end %>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p>No club memberships</p>
<% end %>

<ul>
  <% @user.ratings.each do |rating| %>
    <li class="rating">
      <%= rating %>
      <% if @user == current_user %>
        <%= link_to 'delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @user == current_user %>
  <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>


<% if current_user.admin? %>
  <%= link_to 'Freeze account', freeze_url(id:@user.id), method: :post %>
<% end %>